server:
  port: 8082
spring:
  application:
    name: authenticationService
  rabbitmq:
    addresses: localhost:5672
  datasource:
    password: test
    url: jdbc:postgresql://localhost:5432/authDB
    username: bitblizz
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
  profiles:
    active: test


eureka:
  client:
    service-url:
     defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true